### ISSUE TITLE
Author 항목 업데이트

### ISSUE THREAD

**Issue by ksron** [ComTalk/ComTalk.github.io#15]
- [_data/authors.yml](https://github.com/ComTalk/ComTalk.github.io/blob/03f6d0b97ddade0454f638b88c354e3dc9ceeca2/_data/authors.yml)에서 author 항목 추가

- 예시:

```yml
ksron:
  name : "Sharon Kim" //이름
  bio  : "" // 상태
  avatar : "/assets/images/bio-ksron-avatar.png" // 아바타 
  links: // 연관 링크들
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:kasrlmoojoo@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ksron"
```
